import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/utils/provider";
import SideBar from "./_components/side-bar";
import "./globals.css";
import Navbar from "./_components/nav-bar";
import { DeleteModalProvider } from "@/context/delete-modal-context";
import { createClient } from "@/utils/supabase/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return (
    <html lang="en">
      <body className={`min-h-screen ${inter.className}`}>
        {<Navbar user={user} />}
        {user && <SideBar />}
        <Providers>
          <DeleteModalProvider>
            <div className={user ? "ml-56" : "pl-0"}>{children}</div>
          </DeleteModalProvider>
        </Providers>
      </body>
    </html>
  );
}
