import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/utils/provider";
import { auth } from "@/auth";
import SideBar from "./_components/side-bar";
import "./globals.css";
import Navbar from "./_components/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen ${inter.className}`}>
        {/* {<Navbar user={user} />}
        {user && <SideBar />} */}
        <Providers>
          <div
          // className={user ? "ml-56" : "pl-0"}
          >
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
